import fs from 'fs';
import path from 'path';
import { glob } from 'glob';
import { execSync } from 'child_process';

const TEMP_DIR = 'temp_l10n_extract';
const L10N_DIR = 'l10n';
const SEED_FILE = 'scripts/mdb-category-ids.json';

// The MDB category labels are looked up dynamically via
// `vscode.l10n.t(\`mdb.category.${id}\`)`, so no literal call site carries
// these keys. They are seeded here (generated by
// scripts/generate-mdb-category-labels.mjs) so the scanner considers them
// reachable and the bundles stay complete.
const CATEGORY_SEED = JSON.parse(fs.readFileSync(SEED_FILE, 'utf8'));

function extractFromSvelte(content) {
    let scriptContent = '';
    let templateContent = content;

    // Extract script blocks
    const scriptRegex = /<script[^>]*>([\s\S]*?)<\/script>/g;
    let match;
    while ((match = scriptRegex.exec(content)) !== null) {
        scriptContent += match[1] + '\n;\n';
        // Remove script from template content to avoid double processing
        templateContent = templateContent.replace(match[0], '');
    }

    // Extract l10n.t calls from template
    // Simple parser to handle nested parentheses and strings
    let extraCalls = '';
    const l10nRegex = /\bl10n\.t\s*\(/g;
    while ((match = l10nRegex.exec(templateContent)) !== null) {
        const startIndex = match.index;
        let currentIndex = startIndex + match[0].length;
        let parenDepth = 1;
        let inString = null; // ' or " or `
        let isEscaped = false;

        while (currentIndex < templateContent.length && parenDepth > 0) {
            const char = templateContent[currentIndex];

            if (inString) {
                if (isEscaped) {
                    isEscaped = false;
                } else {
                    if (char === '\\') {
                        isEscaped = true;
                    } else if (char === inString) {
                        inString = null;
                    }
                }
            } else {
                if (char === "'" || char === '"' || char === '`') {
                    inString = char;
                } else if (char === '(') {
                    parenDepth++;
                } else if (char === ')') {
                    parenDepth--;
                }
            }
            currentIndex++;
        }

        if (parenDepth === 0) {
            extraCalls += templateContent.substring(startIndex, currentIndex) + ';\n';
        }
    }

    return scriptContent + '\n// Extracted from template:\n' + extraCalls;
}

// Generates a virtual module whose literal vscode.l10n.t(...) calls cover the
// dynamically-addressed keys. Literal call sites elsewhere in src/ and
// webviews/src/ are found by the scanner itself; only the dynamic
// `mdb.category.<id>` lookups need seeding.
function buildSeedModule() {
    return CATEGORY_SEED.map(id => `vscode.l10n.t(${JSON.stringify(`mdb.category.${id}`)});`).join('\n');
}

async function main() {
    // Clean up temp dir
    if (fs.existsSync(TEMP_DIR)) {
        fs.rmSync(TEMP_DIR, { recursive: true, force: true });
    }
    fs.mkdirSync(TEMP_DIR, { recursive: true });

    // Snapshot current bundles so we can merge and detect losses.
    const bundleFiles = ['bundle.l10n.json', 'bundle.l10n.zh-cn.json', 'bundle.l10n.id.json'];
    const before = Object.fromEntries(bundleFiles.map(f => [
        f, fs.existsSync(path.join(L10N_DIR, f))
            ? JSON.parse(fs.readFileSync(path.join(L10N_DIR, f), 'utf8'))
            : {},
    ]));

    // Process Svelte files
    const svelteFiles = await glob('webviews/src/**/*.svelte');
    for (const file of svelteFiles) {
        const content = fs.readFileSync(file, 'utf8');
        const tsContent = extractFromSvelte(content);

        const relPath = path.relative('webviews/src', file);
        const destPath = path.join(TEMP_DIR, relPath + '.ts');

        fs.mkdirSync(path.dirname(destPath), { recursive: true });
        fs.writeFileSync(destPath, tsContent);
    }

    // Seed module: the dynamic keys only.
    fs.writeFileSync(
        path.join(TEMP_DIR, '_seed_keys.ts'),
        'import * as vscode from "vscode";\n' + buildSeedModule()
    );

    // Run the pinned local vscode-l10n-dev (never npx — version drift would
    // silently change the export format or merge semantics).
    // We include 'src' (original TS files) and 'temp_l10n_extract' (processed
    // Svelte files + seed module).
    const command = 'pnpm exec vscode-l10n-dev export --outDir ./l10n ./src ./webviews/src ./temp_l10n_extract';
    console.log(`Running: ${command}`);
    try {
        execSync(command, { stdio: 'inherit' });
    } catch (e) {
        console.error('l10n export failed');
        process.exit(1);
    }

    // ---- merge pass ----
    // The exporter rewrites bundles wholesale, dropping keys it could not see.
    // Re-add anything that existed before and is still referenced by the seed.
    // Restoration anchor: ONLY the dynamically-addressed keys. Literal call
    // sites are re-scanned fresh every run; anything they no longer reference
    // is dead and must be allowed to disappear (guarded below).
    const seedKeys = new Set(CATEGORY_SEED.map(id => `mdb.category.${id}`));

    // The seeded mdb.category.<id> keys have no literal message, so the
    // exporter fills them with the raw key string (its no-message default).
    // Rebuild them deterministically from the generated table instead: en
    // carries the label, translated bundles keep whatever the generator
    // migrated, anything else falls back to the English label.
    const tableSrc = fs.readFileSync('src/editors/mdbTextDataCategories.ts', 'utf8');
    const enLabels = Object.fromEntries(
        [...tableSrc.matchAll(/"(\d+)": "([^"]*)",/g)].map(m => [m[1], m[2]])
    );
    if (Object.keys(enLabels).length !== CATEGORY_SEED.length) {
        console.error(
            `GUARD FAILED: generated table has ${Object.keys(enLabels).length} ids, seed has ${CATEGORY_SEED.length}.` +
            ' Regenerate with scripts/generate-mdb-category-labels.mjs before exporting.'
        );
        process.exit(1);
    }

    for (const f of bundleFiles) {
        const outPath = path.join(L10N_DIR, f);
        const exported = JSON.parse(fs.readFileSync(outPath, 'utf8'));
        let restored = 0;
        for (const k of Object.keys(before[f])) {
            if (exported[k] === undefined && seedKeys.has(k)) {
                exported[k] = before[f][k];
                restored++;
            }
        }
        for (const [id, label] of Object.entries(enLabels)) {
            const key = `mdb.category.${id}`;
            if (f === 'bundle.l10n.json') {
                exported[key] = label;
            } else {
                const prev = before[f][key];
                // keep a real translation; replace raw-key garbage or fill gaps
                exported[key] = prev !== undefined && prev !== key ? prev : label;
            }
        }
        fs.writeFileSync(outPath, JSON.stringify(exported, null, 4) + '\n');
        console.log(`${f}: ${Object.keys(exported).length} keys (${restored} restored from previous bundle)`);
    }

    // ---- guard + finalize ----
    // Dynamic keys must be present; dropped keys must be provably dead.
    const afterEn = JSON.parse(fs.readFileSync(path.join(L10N_DIR, 'bundle.l10n.json'), 'utf8'));
    for (const id of CATEGORY_SEED) {
        const key = `mdb.category.${id}`;
        if (afterEn[key] === undefined) {
            console.error(`GUARD FAILED: ${key} missing from en bundle after export`);
            process.exit(1);
        }
    }
    console.log(`guard passed: all ${CATEGORY_SEED.length} mdb.category.* keys present in en bundle`);

    // A dropped key is acceptable only if its text occurs nowhere in the
    // scanned source trees (check the escaped-apostrophe variant too, since
    // source literals escape quotes differently than bundle keys do).
    function collectSource(dir) {
        let acc = '';
        for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
            const p = path.join(dir, entry.name);
            if (entry.isDirectory()) acc += collectSource(p);
            else if (/\.(ts|js|mjs|svelte)$/.test(entry.name)) acc += fs.readFileSync(p, 'utf8');
        }
        return acc;
    }
    const srcText = collectSource('src') + collectSource('webviews/src');
    const dropped = Object.keys(before['bundle.l10n.json']).filter(k => afterEn[k] === undefined);
    const stale = [];
    for (const k of dropped) {
        if (srcText.includes(k) || srcText.includes(k.replace(/'/g, "\\'"))) {
            console.error(`GUARD FAILED: live key vanished from the bundle: ${k}`);
            process.exit(1);
        }
        stale.push(k);
    }
    console.log(`guard passed: ${stale.length} dropped keys have no remaining call site`);

    // ---- non-en bundles: mirror the en key set exactly ----
    // vscode-l10n-dev only writes the default bundle, so the translated ones
    // are rebuilt here: keep the previous translation when one exists, fall
    // back to the English value otherwise (new/untranslated content).
    for (const f of ['bundle.l10n.zh-cn.json', 'bundle.l10n.id.json']) {
        const prev = before[f];
        const next = {};
        for (const [k, enVal] of Object.entries(afterEn)) {
            next[k] = prev[k] !== undefined ? prev[k] : enVal;
        }
        fs.writeFileSync(path.join(L10N_DIR, f), JSON.stringify(next, null, 4) + '\n');
        const carried = Object.keys(next).filter(k => prev[k] !== undefined).length;
        console.log(`${f}: ${Object.keys(next).length} keys (${carried} carried over from previous bundle)`);
    }

    // Cleanup
    fs.rmSync(TEMP_DIR, { recursive: true, force: true });
    console.log('Done.');
}

main();
